name: âœ… PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  branch-naming:
    name: ğŸ·ï¸ Check Branch Naming
    if: ${{ !contains('dependabot', github.head_ref) }}
    uses: goby33/gobert--aero-delivery--workflows
    secrets: inherit

  branch-up-to-date:
    name: ğŸ†• Check Branch Up to Date
    uses: goby33/gobert--aero-delivery--workflows/.github/workflows/pr-checks-branch-up-to-date.yaml
    secrets: inherit

  changelog:
    name: ğŸ““ Check Changelog
    if: ${{ !contains('dependabot', github.head_ref) }}
    uses: goby33/gobert--aero-delivery--workflows/.github/workflows/pr-checks-changelog.yaml
    secrets: inherit

  commit:
    name: ğŸ“ Check Commit
    uses: goby33/gobert--aero-delivery--workflows/.github/workflows/pr-checks-commit.yaml
    secrets: inherit

  update-labels:
    name: ğŸ·ï¸ Update labels of PR
    if: ${{ github.event.action == 'opened' }}
    uses: goby33/gobert--aero-delivery--workflows/.github/workflows/pr-update-labels.yaml
    secrets: inherit
